spring.application.name=communication
server.port=8080
# 1. The Database URL (Points to localhost:5432 and the 'communication_db' database)
spring.datasource.url=jdbc:postgresql://localhost:5432/communication_db

# 2. The Credentials (Matches the -e variables from your Docker command)
spring.datasource.username=kumar
spring.datasource.password=kumar

# 3. Hibernate Settings
# 'update' tells Spring to automatically create the 'python_messages' table when you hit Run
spring.jpa.hibernate.ddl-auto=update

# Optional: Shows the exact SQL queries Spring is running in your VS Code terminal
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.consumer.group-id=chat-database-workers
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.auto-offset-reset=earliest

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
# Tell Spring Boot to stop trying to manage Docker
spring.docker.compose.enabled=false