spring.application.name=demo
spring.port=5412
spring.main.web-application-type=none

spring.datasource.url=jdbc:postgresql://localhost:5412/db
spring.datasource.username=kumar
spring.datasource.password=1234
spring.datasource.driver-class-name=org.postgresql.Driver

spring.h2.console.enabled=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa..properties.hibernate.format-sql=true



