version: "3.8"

services:
  springboot-app:
    build: .
    container_name: springboot-backend
    ports:
      - "8080:8080"

    environment:
      # 1. Tells Spring Boot to listen to the Kafka broker via your laptop's loopback network
      - SPRING_KAFKA_BOOTSTRAP_SERVERS=host.docker.internal:9092

      # 2. Points the JPA database connection directly out to your local PostgreSQL instance
      - SPRING_DATASOURCE_URL=jdbc:postgresql://host.docker.internal:5432/communication_db

    # Automates finding your computer's changing network IP on autopilot
    extra_hosts:
      - "host.docker.internal:host-gateway"
